name: Detect PR Type

on:
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches:
      - master

jobs:
  action_on_pr_type:
    runs-on: ubuntu-20.04
    env:
      IS_CLOSED_PR: ${{ github.event.action != 'closed' }}
    steps:
      - name: Detect PR type
        run: |
          echo "IS_CLOSED_PR: ${{ env.IS_CLOSED_PR }}"
