name: Surge PR Preview - Build Stage

on:
  pull_request:
    paths:
      - '.github/worflows/surge-build-artifact.yml'
      - '.github/worflows/surge-upload.yml'
      - 'public/docs/index.html'
      
jobs:
  build-preview:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build fake demo
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          mkdir site
          cp -r public/docs/index.html ./site
      - name: upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-build-dist
          path: site/